# Generated by Django 6.1.1 on 2026-09-15 09:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='نادي الكونغ فو', max_length=100, verbose_name='اسم النادي')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('200'), max_digits=10, verbose_name='اشتراك الشهر')),
                ('session_fee', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=10, verbose_name='سعر الحصة')),
                ('currency', models.CharField(default='ج.م', max_length=10, verbose_name='العملة')),
            ],
            options={
                'verbose_name': 'إعدادات النادي',
                'verbose_name_plural': 'إعدادات النادي',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('group', models.CharField(choices=[('juniors', 'الصغار'), ('seniors', 'الكبار')], default='juniors', max_length=10, verbose_name='المجموعة')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='الموبايل')),
                ('custom_monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='اشتراك خاص')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='خصم شهري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لاعب',
                'verbose_name_plural': 'اللاعبون',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['group'], name='club_player_group_60967a_idx'), models.Index(fields=['is_active'], name='club_player_is_acti_7b6017_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('kind', models.CharField(choices=[('session', 'حصة'), ('month', 'شهر'), ('custom', 'دفعة')], default='custom', max_length=10, verbose_name='النوع')),
                ('method', models.CharField(choices=[('cash', 'كاش'), ('instapay', 'إنستاباي'), ('wallet', 'محفظة'), ('other', 'أخرى')], default='cash', max_length=10, verbose_name='طريقة الدفع')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='club.player')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['year', 'month'], name='club_paymen_year_01c76f_idx'), models.Index(fields=['player', 'year', 'month'], name='club_paymen_player__b7da98_idx')],
            },
        ),
    ]
